package uk.org.cse.nhm.energycalculator.api.types;

public enum ServiceType {
	INTERNALS,
	SOLAR_GAINS,
	COOKING, 
	LIGHTING, 
	SINKS, 
	APPLIANCES,
	PRIMARY_SPACE_HEATING,
	SECONDARY_SPACE_HEATING, 
	METABOLIC_GAINS, 
	WATER_HEATING,
	GENERATION
}
