package uk.org.cse.nhm.energy.util;

import uk.org.cse.nhm.energycalculator.api.types.steps.EnergyCalculationStep;

import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.StringWriter;

/**
 * Inspects EnergyCalculationStep.java and generates the following: 1.
 * XEnergyCalculationStep.java 2. MapEnum.energyCalculationstepMapping
 */
public class EnergyCalculationStepsGenerator {

    public static void main(final String[] args) throws FileNotFoundException {
        boolean e = true;
        PrintStream out = System.out;

        if (args.length > 0) {
            out = new PrintStream(args[0]);
            e = args[0].endsWith(".java");
        }

        if (e) {
            writeEnum(out);
        } else {
            writeTable(out);
        }
    }

    public static void writeTable(final PrintStream out) {
        out.println("Step\tLocation\tConversion");

        for (EnergyCalculationStep step : EnergyCalculationStep.values()) {
            if (!step.isSkipped()) {
                out.println(
                        String.format("%s\t%s\t%s",
                                step.name(),
                                step.sapLocation,
                                step.conversion
                        )
                );
            }
        }
    }

    public static void writeEnum(final PrintStream out) {
        final StringWriter enumStr = new StringWriter();
        final StringWriter mapStr = new StringWriter();
        final PrintWriter enumDef = new PrintWriter(enumStr);
        final PrintWriter mapDef = new PrintWriter(mapStr);

        writeEnumHead(enumDef);
        writeMapHead(mapDef);

        for (EnergyCalculationStep step : EnergyCalculationStep.values()) {
            if (!step.isSkipped()) {
                writeEnumValue(enumDef, step);
                writeMapValue(mapDef, step);
            }
        }

        writeEnumFoot(enumDef);
        writeMapFoot(mapDef);

        out.println(enumStr.toString());
        out.println(mapStr.toString());
    }

    private static void writeMapHead(PrintWriter mapDef) {
        mapDef.println("/** Generated by EnergyCalculationstepsGenerate.java */");
        mapDef.println("final static Map<XEnergyCalculationStep, EnergyCalculationStep> energyCalculationStepMapping = ImmutableMap.<XEnergyCalculationStep, EnergyCalculationStep>builder()");
    }

    private static void writeMapValue(PrintWriter mapDef, EnergyCalculationStep step) {
        mapDef.println(String.format(
                ".put(XEnergyCalculationStep.%s, EnergyCalculationStep.%s)",
                step.name(),
                step.name()
        ));
    }

    private static void writeMapFoot(PrintWriter mapDef) {
        mapDef.println(".build();");
    }

    private static void writeEnumHead(PrintWriter enumDef) {
        enumDef.println("package uk.org.cse.nhm.language.definition.enums;");
        enumDef.println();
        enumDef.println("import uk.org.cse.nhm.language.definition.Category;");
        enumDef.println("import uk.org.cse.nhm.language.definition.Category.CategoryType;");
        enumDef.println("import uk.org.cse.nhm.language.definition.Doc;");
        enumDef.println();
        enumDef.println("/** Generated by EnergyCalculationstepsGenerate.java */");
        enumDef.println("@Doc({");
        enumDef.println("\"Steps in the SAP 2012 worksheet http://www.bre.co.uk/filelibrary/SAP/2012/SAP-2012_9-92.pdf which can be output by the model.\",");
        enumDef.println("\"In the future, it may be extended to include steps from BREDEM 2012.\"");
        enumDef.println("})");
        enumDef.println("@Category(CategoryType.CATEGORIES)");
        enumDef.println("public enum XEnergyCalculationStep {");
    }

    private static void writeEnumValue(PrintWriter enumDef, EnergyCalculationStep step) {
        enumDef.println("@Doc({");

        enumDef.println("\"" + step.sapLocation.toString() + "\",");

        enumDef.println("\"" + step.getDefaultText() + "\",");

        enumDef.println("\"" + step.period.toString() + "\",");

        enumDef.println("\"" + step.conversion.toString() + "\"");

        enumDef.println("})");
        enumDef.println(step.name() + ",");
    }

    private static void writeEnumFoot(PrintWriter enumDef) {
        enumDef.println(";");
        enumDef.println("}");
    }
}
